[theme]
base                  = "dark"
primaryColor          = "#ffb300"
backgroundColor       = "#060a12"
secondaryBackgroundColor = "#0d1526"
textColor             = "#f0f6ff"
font                  = "sans serif"

[server]
headless              = true
enableStaticServing   = false

[browser]
gatherUsageStats      = false
